val patterns = arrayOf(
    "{s} {s}",
    "{s} {p}",
    "The {s} of {c} {p}",
    "The {c} {p} of {s}",
    "{s} and the {c} {p}",
    "{s} of {s} and {s}",
    "{s} of {p}",
    "{p} of the {s}",
    "{s}'s {s}",
    "The {s}'s {c} {p}",
    "{s}: The {s}",
    "{s}: The {p}",
    "{s}: {s} and the {c} {p}",
    "{s}: {s} of {s} and {s}",
    "{s}: {s} {p}",
    "{p}: {s} {p}",
    "{s} of {p}: {s} and {s}",
    "{p} of {s}: The {s} {p}",
    "{s} {s}: {s} of the {s}",
    "{s} {s}: {s} of {p}",
    "{s} {p}: {p} of the {s}",
    "{s} {p}: {c} {p} of the {s}",
    "{s} {p}: {p} of {s}"
)
