val words = setOf(
    Word("Adventure"),
    Word("Age"),
    Word("Agent"),
    Word("Angel"),
    Word("Arena"),
    Word("Avalon", ""),
    Word("Bandit"),
    Word("Bane", ""),
    Word("Banshee"),
    Word("Bard"),
    Word("Battle"),
    Word("Black", ""),
    Word("Blade"),
    Word("Call"),
    Word("Castle"),
    Word("Cave"),
    Word("Chaos", ""),
    Word("Chronicle"),
    Word("Clan"),
    Word("Cloud"),
    Word("Conquest"),
    Word("Crest"),
    Word("Crusade"),
    Word("Dagger"),
    Word("Darkness", ""),
    Word("Defeat", ""),
    Word("Defender"),
    Word("Defense", ""),
    Word("Demon"),
    Word("Destiny", pluralOverride = "Destinies"),
    Word("Destroyer"),
    Word("Devil"),
    Word("Dominion"),
    Word("Dragon"),
    Word("Duel"),
    Word("Dungeon"),
    Word("Dynasty", pluralOverride = "Dynasties"),
    Word("Eternal"),
    Word("Emperor"),
    Word("Empire"),
    Word("Endless", ""),
    Word("Epic"),
    Word("Era"),
    Word("Fate"),
    Word("Fire"),
    Word("Flame"),
    Word("Fortune"),
    Word("Galaxy", pluralOverride = "Galaxies"),
    Word("Game"),
    Word("Ghost"),
    Word("Gladiator"),
    Word("Glory", pluralOverride = "Glories"),
    Word("Glyph"),
    Word("Goblin"),
    Word("God"),
    Word("Goddess", "es"),
    Word("Guardian"),
    Word("Gun"),
    Word("Harbinger"),
    Word("Hero", "es"),
    Word("Iron"),
    Word("Ice", ""),
    Word("Illusion"),
    Word("Keep", ""),
    Word("King"),
    Word("Kingdom"),
    Word("Knight"),
    Word("League"),
    Word("Legend"),
    Word("Legion"),
    Word("Lord"),
    Word("Magic", ""),
    Word("Mask"),
    Word("Mobile", ""),
    Word("Monster"),
    Word("Moon"),
    Word("Mystery", pluralOverride = "Mysteries"),
    Word("Night"),
    Word("Ogre"),
    Word("Orc"),
    Word("Order", ""),
    Word("Overlord"),
    Word("Phantom"),
    Word("Pharaoh"),
    Word("Phoenix", "es"),
    Word("Poem"),
    Word("Priest"),
    Word("Priestess", "es"),
    Word("Prince"),
    Word("Princess", "es"),
    Word("Quest"),
    Word("Raid"),
    Word("Rift"),
    Word("Rise", ""),
    Word("Road"),
    Word("Ronin"),
    Word("Rose"),
    Word("Rune"),
    Word("Sacrifice"),
    Word("Samurai", ""),
    Word("Savior"),
    Word("Scroll"),
    Word("Sea"),
    Word("Seven", ""),
    Word("Shadow"),
    Word("Shield"),
    Word("Sin"),
    Word("Siren"),
    Word("Skill"),
    Word("Skull"),
    Word("Son"),
    Word("Song"),
    Word("Soul"),
    Word("Spell"),
    Word("Squire"),
    Word("Star"),
    Word("Steel", ""),
    Word("Storm"),
    Word("Strategy", pluralOverride = "Strategies"),
    Word("Sultan"),
    Word("Summoner"),
    Word("Sun"),
    Word("Sword"),
    Word("Tactics", ""),
    Word("Tale"),
    Word("Throne"),
    Word("Titan"),
    Word("Trial"),
    Word("Tribe"),
    Word("Troll"),
    Word("Universe"),
    Word("Victory", pluralOverride = "Victories"),
    Word("War"),
    Word("Warlock"),
    Word("Warrior"),
    Word("Witch", "es"),
    Word("Wizard"),
    Word("World")
)
