val words = setOf(
    Word("Adventure"),
    Word("Age"),
    Word("Avalon", ""),
    Word("Battle"),
    Word("Crusade"),
    Word("Dominion"),
    Word("Dynasty", pluralOverride = "Dynasties"),
    Word("Eternal"),
    Word("Empire"),
    Word("Endless", ""),
    Word("Epic"),
    Word("Era", ""),
    Word("Fire"),
    Word("Flame"),
    Word("Fortune"),
    Word("Game"),
    Word("Glory", pluralOverride = "Glories"),
    Word("Gun"),
    Word("Hero", "es"),
    Word("Iron"),
    Word("Ice", ""),
    Word("Kingdom"),
    Word("Knight"),
    Word("Legend"),
    Word("Lord"),
    Word("Magic", ""),
    Word("Mask"),
    Word("Mobile", ""),
    Word("Mystery", pluralOverride = "Mysteries"),
    Word("Pharaoh"),
    Word("Raid"),
    Word("Rise", ""),
    Word("Road"),
    Word("Scroll"),
    Word("Seven", ""),
    Word("Shadow"),
    Word("Steel", ""),
    Word("Summoner"),
    Word("War")
)
